# CHECKED

from enum import Enum, StrEnum

class GoodType(StrEnum):
    LEMN_ROTUND = "Lemn rotund"
    LEMN_FOC = "Lemn de foc"
    CHERESTELE = "Cherestele"
    UNKNOWN = "Necunoscut"

# ---------------------------------------------------------------------- #

class DepositType(StrEnum):
    """List of possible deposit types used by the app."""
    DEPOZIT_PRINCIPAL = "Depozit principal"       # from SUMAL
    DEPOZIT_TEMPORAR_LR = "Depozit temporar LR"   # from SUMAL
    DEPOZIT_EXTERN = "Depozit extern"             # generated by the app, external deposit deduced from a notice
    UNKNOWN = "Necunoscut"

# ---------------------------------------------------------------------- #

class NoticeType(StrEnum):
    INTRARE_DIN_PARTIDA_PROPRIE = "Intrare din partidă proprie"
    INTRARE_DIN_SURSA_EXTERNA = "Intrare din sursa externă"
    IESIRE_DIN_DEPOZIT_PRINCIPAL = "Ieșire din depozit principal"
    IESIRE_DIN_DEPOZIT_LR = "Ieșire din depozit LR"
    UNKNOWN = "Necunoscut"

# ---------------------------------------------------------------------- #

class AppState(Enum):
    WAITING = "waiting"
    READY = "ready"
    PROCESSING = "processing"
    SUCCESS = "success"
    PROCESSED_WITH_ERRORS = "processed_with_errors"
    REPORT_COMPLETE = "report_complete"

# ---------------------------------------------------------------------- #

class DepozitSource(StrEnum):
    EXCEL_SUMAL = "Excel SUMAL"
    AVIZE = "Avize"

# ---------------------------------------------------------------------- #

class SUMALDepositType(StrEnum):
    """Deposit type strings from SUMAL format.
    'Depozit' = depozit principal - depozitul prorpiu;
    'Depozit Temporar LR' = partida exploatare"""
    DEPOZIT = "Depozit"
    DEPOZIT_TEMPORAR_LR = "Depozit Temporar LR"

# ---------------------------------------------------------------------- #

class FolderStatus(Enum):
    NO_FILES = "no_files"
    MISSING_XL = "missing_xl"
    MISSING_CSV = "missing_csv"
    READY = "ready"


# ---------------------------------------------------------------------- #

class CSVParseStatus(Enum):
    OK = "OK"
    ERROR = "ERROR"